# -*- coding: utf-8 -*-
"""Differential Equation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izo2XMf2a7Nplv0o5XlSzkHiCaMKLTdc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error
plt.style.use('seaborn-v0_8-paper')

def euler(t0, q0, delta_T, N, RC):
  Q = [q0]
  T = [t0]
  for i in range(N):
    Q.append(Q[-1]*(1 - delta_T/RC))
    T.append(T[-1] + delta_T)
  return np.array(Q), np.array(T)
#i use q0 = 1000, t0=0, delta T = 0.01, N = 1000,000 and RC = 1000
Q, T = euler(0, 1000, 0.01, 1000000, 1000)

'''
analytical solution is q = q0*exp(-t/RC)
'''
real_q = 1000 * np.exp(-T/1000)

plt.plot(T, real_q, linestyle='--', color='g', label='Real values', linewidth=2.5)
plt.scatter(x=T, y=Q, c='r', s=10, label="Euler's approximation")
plt.xlabel('Time')
plt.ylabel('Q(Electric Charge)')
plt.legend()
plt.show()

mse = mean_squared_error(real_q, Q)
mse

