# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sD8LrfvSd6BuD_VpzEs77L9dhOYVk_e

# **fractals problems**
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
style.use('seaborn-v0_8')

"""Creating Kokh fractal.
I crate this fractal using 4,functions:

one will do transformation.

one will do rotation as much as e want!(we can write two functions for rotation,60 degrees rotation and -60 degrees rotation;but for generalization i will write a function to perform arbitrary rotation)

last function will put toghether these functions and create the fractal.
"""

def transform(x,a):
  return x+a
def rotate(x,theta):
  rotation_matrix=np.array([[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])
  return np.dot(rotation_matrix,x)

#now that we have built the basic functions lets make the fractal

def kokh(x,n):
  for i in range(n):
    #for k in range(len(x)):
    x=x/3#for scaling
    x2=rotate(x.T,np.pi/3).T
    x2=transform(x2,x[-1])
    #lets create the other one
    x3=rotate(x.T,-np.pi/3).T
    x3=transform(x3,x2[-1])
    #now lets craete the right tail
    x4=transform(x,x3[-1])
    x=np.vstack((x,x2,x3,x4))

  plt.plot(x[:,0],x[:,1],color='black',marker=None)
  plt.xlim()
  plt.ylim(bottom=-.2,top=1)
  plt.title(f'Kokh Curve-order {n}')
  plt.show()

x_init = np.array([[0, 0], [1, 0]])

kokh(x_init, 10)

#now lets pass a traingle
x_init = np.array([[0, 0],[1,1],[2,0]])
kokh(x_init, 10)

